base:
  model_name: c3pi_gold_std
  organism: human
  train_pair_dir: /home/mohsenh/projects/def-ilie/mohsenh/ppi/dataset/pairs/gold_std_train.tsv
  validation_pair_dir: /home/mohsenh/projects/def-ilie/mohsenh/ppi/dataset/pairs/gold_std_validation.tsv
  test_pair_dir: /home/mohsenh/projects/def-ilie/mohsenh/ppi/dataset/pairs/gold_std_test.tsv
  embedding_dir: /home/mohsenh/projects/def-ilie/mohsenh/ppi/dataset/embd/gold_std/
  checkpoint_dir: checkpoints/
  result_dir: results/
  output_dir: outputs/
  tb_log_dir: logs/tb_gold_logs/
  log_dir: logs/
  plot_dir: plots/
  
model:
  num_epochs: 20
  batch_size: 64

