base:
  model_name: c3pi_gold_std
  organism: human
  train_pair_dir: /path/to/train/gold_std_train.tsv
  validation_pair_dir: /path/to/validation/gold_std_validation.tsv
  test_pair_dir: /path/to/test/gold_std_test.tsv
  embedding_dir: /path/to/embdding/gold_std/
  checkpoint_dir: /path/to/checkpoints/
  result_dir: /path/to/results/
  output_dir: /path/to/outputs/
  tb_log_dir: /path/to/logs/tb_gold_logs/
  log_dir: /path/to/logs/
  plot_dir: /path/to/plots/
  
model:
  num_epochs: 20
  batch_size: 64

